spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: dev_user
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true